name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Generate Time-Based Tag
        id: time_tag
        run: echo "time_tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: ./we-broke/
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.time_tag.outputs.time_tag }}
