name: Deploy to Raspberry Pi

on:
  workflow_dispatch:  # only manual run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          port: 2222
          script: |
            cd /kactus-we-broke/we-broke
            docker compose pull
            docker compose up -d
